# Generated by Django 4.0 on 2021-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_votes_to_skip_room_vote_to_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_can_pause_music',
            field=models.BooleanField(default=True),
        ),
    ]
